% For using a color image (or any image that was not used for the
% quantitation)to plot the direction on top of.  Requires a new
% input, "imagename", which points to the color image. Uses variables
% generated by wholecell_cap.m  This can use a color image, and can resize
% the image by a factor "scale"

clear F;
writerobj = [];

anglelines =[];
scale = 5;
moviename = 'WT_0_150_11_5_12';

imagename = '/Users/AmyAllen/Documents/ThesisWork/Microscopy/Gradient for Methods/2018_10_02/S2_2018-10-02_WT_150nM_gradient/S2_2018-10-02_WT_150nM_gradient-mask.tif';

colorin = [];%variable holding the image data
tmax = size(imfinfo(imagename));

%% load image data
for i = 1:tmax;
    colorin{i,1} = imread(imagename,i);
    % optional scaling of the image, requires scaling of the markers
    colorin{i,1}=imresize(colorin{i,1},scale);
end

%% calculate lines
for i = 1:size(tracked,1);
    for t = 1:tnum;
    anglelines{i,t}(1,1)=centroids{i,1}(t,1)*scale; % High x
    anglelines{i,t}(1,2)=centroids{i,1}(t,2)*scale; % High y
    anglelines{i,t}(2,1)=centroids{i,1}(t,1)*scale+15*cosd(cellangles{i,1}(t,1))*scale/2;
    anglelines{i,t}(2,2)=centroids{i,1}(t,2)*scale+15*sind(cellangles{i,1}(t,1))*scale/2;
    end
end

% make the movie
figure('Position', [10,10,800,800])
for i = 1:tnum;
    imshow(colorin{i,1});
    for j = 1:size(tracked,1);
    if isempty(centroids{j,1}(i,:)) ==0;
        hold on
        plot(centroids{j,1}(i,1)*scale,centroids{j,1}(i,2)*scale, 'Marker', 'o','MarkerFaceColor','none','MarkerEdgeColor','k','LineStyle','none');
        plot(centroids{j,1}(i,3)*scale,centroids{j,1}(i,4)*scale, 'Marker', 'x','MarkerEdgeColor','r','LineStyle','none');
                   
        
            plot(anglelines{j,i}(:,1),anglelines{j,i}(:,2), 'k', 'Marker', 'none');
        
        hold off
    else
    end
    end
    
    
    F(i) = getframe;
end
writerobj = VideoWriter([moviename,'.avi'], 'Uncompressed AVI');
open(writerobj);
writeVideo(writerobj, F);
close(writerobj);